version: '3.6'

services:
  bazel-cache:
    container_name: bazel-remote-cache
    image: buchgr/bazel-remote-cache:latest
    restart: always
    ports:
      - 9090:8080
      - 9092:9092
    command: --max_size=1000
    volumes:
      - /path/to/cache/dir:/data
    environment:
      BAZEL_REMOTE_GRPC_PORT: 9092
      # setting data dir and the max_size has no effect here as they are predefined by command line args
      # use the "command" to overwrite it or build your own image with different default parameters
      # see https://stackoverflow.com/q/64341356/13543363
      # BAZEL_REMOTE_DIR: /data
      # BAZEL_REMOTE_MAX_SIZE: 1000
